const menu = [
  {
    id: 1,
    title: "Idly",
    category: "breakfast",
    price: 75,
    img: "https://t3.ftcdn.net/jpg/03/62/02/26/360_F_362022640_fZ6UM0JycJlFDdBiR1pYlNddKfdGvYwR.jpg",
    desc: `Idli or idly are a type of savoury rice cake, originating from the Indian subcontinent, popular as breakfast foods in Southern India and in Sri Lanka. The cakes are made by steaming a batter consisting of fermented black lentils and rice`,
  },
  {
    id: 2,
    title: "Mix Veg",
    category: "lunch",
    price: 110,
    img: "https://khanamanpasand.com/wp-content/uploads/2020/12/mix-veg-recipe-1.jpg",
    desc: `Mix veg curry is made by cooking a mixture of vegetables together in a traditional Indian onion-tomato gravy. The dish is characterized by multiple flavors due to the addition of many vegetables which also makes it quite nutritious.`,
  },
  {
    id: 3,
    title: "Oreo Milkshake",
    category: "shakes",
    price: 30,
    img: "https://www.archanaskitchen.com/images/archanaskitchen/1-Author/Waagmi_Soni/oreo-milkshake-recipe.jpg",
    desc: `ombucha chillwave fanny pack 3 wolf moon street art photo booth before they sold out organic viral.`,
  },
  {
    id: 4,
    title: "Dosa",
    category: "breakfast",
    price: 110,
    img: "https://food.fnr.sndimg.com/content/dam/images/food/fullset/2019/10/9/DV3016_masala-dosa_s4x3.jpg.rend.hgtvcom.616.462.suffix/1570635680579.jpeg",
    desc: `A dosa is a thin pancake or crepe, originating from South India, made from a fermented batter predominantly consisting of lentils and rice. It is somewhat similar to a crepe in appearance, although savoury flavours are generally emphasized`,
  },
  {
    id: 5,
    title: "Bhojanam Thali",
    category: "lunch",
    price: 80,
    img: "https://kinaraindiancuisine.ca/wp-content/uploads/2020/05/Lunch-Thali_Kinaraindiancuisine-scaled.jpg",
    desc: `Thali (meaning "plate") or Bhojanam (meaning "full meal") is a round platter used to serve food in South Asia and Southeast Asia. Thali is also used to refer to an Indian-style meal made up of a selection of various dishes which are served on a platter.`,
  },
  {
    id: 6,
    title: "Coconut Shake",
    category: "shakes",
    price: 60,
    img: "https://www.foodadvisor.my/attachments/a12eb0b5e3cd47cc37109472ff25f13357d16fa2/store/fill/800/500/787e6c9c168a943cef625aee29640984636b2296ba0c0da41a89d8764500/featured_image.jpg",
    desc: `Coconut Shake, an absolute tropical delight to taste buds, is prepared by blending toasted coconut, milk and ice cream and sweetened with sugar to taste.`,
  },
  {
    id: 7,
    title: "Onion Uthappam",
    category: "breakfast",
    price: 63,
    img: "https://www.lekhafoods.com/media/1050768/onion-uthappam.jpg",
    desc: `Uthappam is a type of dosa from South India. In Tamil Nadu it is known as Uthappam, in Karnataka it is known as Uttappa. In Kerala it is known as Oothappam In Tulu it is known as Ootappa or Ootappo. Unlike a typical dosa, which is crisp and crepe-like, uttapam is thicker, with toppings.`,
  },
  {
    id: 8,
    title: "Paneer tikka",
    category: "lunch",
    price: 199,
    img: "https://geekrobocook.com/wp-content/uploads/2021/03/6.-Paneer-Tikka.jpg",
    desc: `Paneer tikka is an Indian dish made from chunks of paneer marinated in spices and grilled in a tandoor. It is a vegetarian alternative to chicken tikka and other meat dishes.`,
  },
  {
    id: 9,
    title: "chocolate protein shake",
    category: "shakes",
    price: 45,
    img: "https://durefoods.com/wp-content/uploads/2016/09/Asset-2.jpg",
    desc: `So simple to make and such a classic flavor combo, this extra rich and creamy Chocolate Banana Protein Shake sure will satisfy after a hard workout, or will start your day on the right foot!`,
  },
];
export default menu;
